// Generated by Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import SceneKit;
@import Foundation;
@import QuartzCore;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("MMDSceneKit_iOS")

SWIFT_CLASS("_TtC15MMDSceneKit_iOS9DummyNode")
@interface DummyNode : NSObject
- (id _Nullable)valueForUndefinedKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SCNPhysicsBehavior;
@class SCNMaterial;
@class SCNGeometryElement;
@class NSValue;
@class MMDFloat;
@class SCNMorpher;
@class CAAnimation;
@class NSCoder;
@class CAAnimationGroup;
@protocol SCNAnimation;
@class SCNScene;

SWIFT_CLASS("_TtC15MMDSceneKit_iOS7MMDNode")
@interface MMDNode : SCNNode <SCNProgramDelegate>
@property (nonatomic, readonly, copy) NSArray<SCNPhysicsBehavior *> * _Null_unspecified physicsBehaviors SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.physicsBehaviors' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL isKnee SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.isKnee' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<SCNPhysicsBehavior *> * _Nullable joints SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.joints' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) NSInteger vertexCount SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.vertexCount' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified vertexArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.vertexArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified normalArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.normalArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified texcoordArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.texcoordArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified boneIndicesArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.boneIndicesArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified boneWeightsArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.boneWeightsArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) NSInteger indexCount SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.indexCount' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified indexArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.indexArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) NSInteger materialCount SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.materialCount' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<SCNMaterial *> * _Null_unspecified materialArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.materialArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified materialIndexCountArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.materialIndexCountArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<SCNGeometryElement *> * _Nullable elementArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.elementArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<MMDNode *> * _Null_unspecified boneArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.boneArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSValue *> * _Null_unspecified boneInverseMatrixArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.boneInverseMatrixArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) MMDNode * _Null_unspecified rootBone SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.rootBone' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) MMDNode * _Nullable rotateEffector SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.rotateEffector' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) float rotateEffectRate SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.rotateEffectRate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) MMDNode * _Nullable translateEffector SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.translateEffector' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) float translateEffectRate SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.translateEffectRate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable faceIndexArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.faceIndexArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSArray<NSNumber *> *> * _Nullable faceDataArray SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.faceDataArray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<MMDFloat *> * _Null_unspecified faceWeights SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.faceWeights' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) SCNMorpher * _Null_unspecified geometryMorpher SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.geometryMorpher' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSDictionary<NSString *, CAAnimation *> * _Nullable preparedAnimation SWIFT_DEPRECATED_OBJC("Swift property 'MMDNode.preparedAnimation' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (MMDNode * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
- (void)updateFace SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.updateFace()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateVertexData SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.updateVertexData()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (id _Nullable)valueForUndefinedKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setValue:(id _Nullable)value forUndefinedKey:(NSString * _Nonnull)key;
- (void)prepareAnimation:(CAAnimation * _Nonnull)animation forKey:(NSString * _Nonnull)key SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.prepareAnimation(_:forKey:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)playPreparedAnimationForKey:(NSString * _Nonnull)key SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.playPreparedAnimation(forKey:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (CAAnimationGroup * _Nonnull)convertAnimation:(CAAnimationGroup * _Nonnull)animation SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.convertAnimation(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)addAnimation:(id <SCNAnimation> _Nonnull)animation forKey:(NSString * _Nullable)key;
/// update IK bone
- (void)updateIK SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.updateIK()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateEffector SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.updateEffector()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)addPhysicsBehaviorWithScene:(SCNScene * _Nonnull)scene SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.addPhysicsBehavior(scene:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)removePhysicsBehaviorWithScene:(SCNScene * _Nonnull)scene SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.removePhysicsBehavior(scene:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (SCNNode * _Nonnull)getRootNode SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.getRootNode()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (SCNVector4)rotationToQuat:(SCNVector4)rot SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.rotationToQuat(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (SCNVector4)quatToRotation:(SCNVector4)quat SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.quatToRotation(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class SCNCamera;

SWIFT_CLASS("_TtC15MMDSceneKit_iOS13MMDCameraNode")
@interface MMDCameraNode : MMDNode
@property (nonatomic) float rotX SWIFT_DEPRECATED_OBJC("Swift property 'MMDCameraNode.rotX' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) float rotY SWIFT_DEPRECATED_OBJC("Swift property 'MMDCameraNode.rotY' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) float rotZ SWIFT_DEPRECATED_OBJC("Swift property 'MMDCameraNode.rotZ' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) float distance SWIFT_DEPRECATED_OBJC("Swift property 'MMDCameraNode.distance' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'MMDCameraNode.init(name:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (SCNNode * _Nonnull)getCameraNode SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDCameraNode.getCameraNode()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (SCNCamera * _Nonnull)getCamera SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDCameraNode.getCamera()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC15MMDSceneKit_iOS8MMDFloat")
@interface MMDFloat : NSObject
@property (nonatomic) float value SWIFT_DEPRECATED_OBJC("Swift property 'MMDFloat.value' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SCNSceneRenderer;

SWIFT_CLASS("_TtC15MMDSceneKit_iOS15MMDIKController")
@interface MMDIKController : NSObject <SCNSceneRendererDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MMDIKController * _Nonnull sharedController SWIFT_DEPRECATED_OBJC("Swift property 'MMDIKController.sharedController' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (MMDIKController * _Nonnull)sharedController SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'MMDIKController.sharedController' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Init function is private for singleton
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
/// update IK constraint for the given renderer
+ (void)updateIKWithRenderer:(id <SCNSceneRenderer> _Nonnull)renderer SWIFT_DEPRECATED_OBJC("Swift method 'MMDIKController.updateIK(renderer:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// apply IK constraint recursively
+ (void)applyIKRecursive:(SCNNode * _Nonnull)node SWIFT_DEPRECATED_OBJC("Swift method 'MMDIKController.applyIKRecursive(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// apply IK constraint after animations are applied
- (void)renderer:(id <SCNSceneRenderer> _Nonnull)renderer didApplyAnimationsAtTime:(NSTimeInterval)time;
@end



@interface MMDNode (SWIFT_EXTENSION(MMDSceneKit_iOS)) <CAAnimationDelegate>
- (void)animationDidStop:(CAAnimation * _Nonnull)anim finished:(BOOL)finished;
- (void)setCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(void))block forPreparedAnimationKey:(NSString * _Nonnull)key SWIFT_DEPRECATED_OBJC("Swift method 'MMDNode.setCompletionHandler(_:forPreparedAnimationKey:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC15MMDSceneKit_iOS10MMDProgram")
@interface MMDProgram : SCNProgram <SCNProgramDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15MMDSceneKit_iOS14MMDSceneSource")
@interface MMDSceneSource : SCNSceneSource
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Initializes a scene source for reading the scene graph contained in an NSData object.
/// \param data A data object containing a scene file in MMD file format.
///
/// \param options ignored. just for compatibility of SCNSceneSource.
///
- (nullable instancetype)initWithData:(NSData * _Nonnull)data options:(NSDictionary<SCNSceneSourceLoadingOption, id> * _Nullable)options;
/// Initializes a scene source for reading the scene graph from a specified file.
/// \param url A URL identifying the location of a scene file in MMD file format.
///
/// \param options ignored. just for compatibility of SCNSceneSource.
///
- (nullable instancetype)initWithURL:(NSURL * _Nonnull)url options:(NSDictionary<SCNSceneSourceLoadingOption, id> * _Nullable)options;
/// Return an array of MMDNode objects which represent model node
- (NSArray<MMDNode *> * _Null_unspecified)modelNodes SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDSceneSource.modelNodes()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (NSArray<MMDNode *> * _Null_unspecified)cameraNodes SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDSceneSource.cameraNodes()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (NSArray<MMDNode *> * _Null_unspecified)lightNodes SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDSceneSource.lightNodes()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (SCNScene * _Nullable)getScene SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDSceneSource.getScene()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (MMDNode * _Nullable)getModel SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDSceneSource.getModel()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Return a hash of CAAnimationGroup
- (NSDictionary<NSString *, CAAnimationGroup *> * _Null_unspecified)animations SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDSceneSource.animations()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (CAAnimationGroup * _Nullable)getMotion SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MMDSceneSource.getMotion()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
